udp:
  ip: 192.168.95.1
  port: 7000
  serverport: 5551
humanset:
  bodyfile: body_unity_pose
  targethandfile: human_hand_info
system:
  usecan: true
  usegui: false
  usenetpub: false
  useudp: true
  useudpserver: true
  usesapien: true
  sapientype: right
  can:
    id: 40
    bitrate: 1000000
    dofs: 25
  robotname_r: l21
  robotname_l: l21
  retargeting_type: projection
  datasource_type: motion
  motion_type: linkerforce
  motion_device: eric
  rightpub: true
  leftpub: true
debug:
  joint_pub_debug: false
  joint_motor_debug_r: false
  joint_motor_debug_l: false
netpub:
  ip: 192.168.11.33
  port: 20008
